# Generated by Django 5.2.9 on 2026-02-24 03:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avocado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firmness", models.FloatField()),
                ("hue", models.IntegerField()),
                ("saturation", models.IntegerField()),
                ("brightness", models.IntegerField()),
                ("sound_db", models.IntegerField()),
                ("weight_g", models.IntegerField()),
                ("size_cm3", models.IntegerField()),
                ("color_category", models.CharField(max_length=64)),
                ("predict", models.CharField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_age", models.IntegerField()),
                ("person_income", models.IntegerField()),
                ("person_emp_exp", models.IntegerField()),
                ("loan_amnt", models.IntegerField()),
                ("loan_int_rate", models.IntegerField()),
                ("loan_percent_income", models.IntegerField()),
                ("cb_person_cred_hist_length", models.IntegerField()),
                ("credit_score", models.IntegerField()),
                ("person_gender", models.CharField(max_length=64)),
                ("person_education", models.CharField(max_length=64)),
                ("person_home_ownership", models.CharField(max_length=64)),
                ("loan_intent", models.CharField(max_length=64)),
                ("previous_loan_defaults_on_file", models.CharField(max_length=64)),
                ("predict", models.FloatField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diabetes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.IntegerField()),
                ("Glucose", models.IntegerField()),
                ("BloodPressure", models.IntegerField()),
                ("SkinThickness", models.IntegerField()),
                ("Insulin", models.IntegerField()),
                ("BMI", models.FloatField()),
                ("DiabetesPedigreeFunction", models.FloatField()),
                ("Age", models.IntegerField()),
                ("predict", models.BooleanField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GrLivArea", models.IntegerField()),
                ("YearBuilt", models.IntegerField()),
                ("GarageCars", models.IntegerField()),
                ("TotalBsmtSF", models.IntegerField()),
                ("FullBath", models.IntegerField()),
                ("OverallQual", models.IntegerField()),
                ("Neighborhood", models.CharField(max_length=64)),
                ("predicted_price", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mushroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cap_shape", models.CharField(max_length=64)),
                ("cap_surface", models.CharField(max_length=64)),
                ("cap_color", models.CharField(max_length=64)),
                ("bruises", models.CharField(max_length=64)),
                ("odor", models.CharField(max_length=64)),
                ("gill_attachment", models.CharField(max_length=64)),
                ("gill_spacing", models.CharField(max_length=64)),
                ("gill_size", models.CharField(max_length=64)),
                ("gill_color", models.CharField(max_length=64)),
                ("stalk_shape", models.CharField(max_length=64)),
                ("stalk_root", models.CharField(max_length=64)),
                ("stalk_surface_above_ring", models.CharField(max_length=64)),
                ("stalk_surface_below_ring", models.CharField(max_length=64)),
                ("stalk_color_above_ring", models.CharField(max_length=64)),
                ("stalk_color_below_ring", models.CharField(max_length=64)),
                ("veil_color", models.CharField(max_length=64)),
                ("ring_number", models.CharField(max_length=64)),
                ("ring_type", models.CharField(max_length=64)),
                ("spore_print_color", models.CharField(max_length=64)),
                ("population", models.CharField(max_length=64)),
                ("habitat", models.CharField(max_length=64)),
                ("poisonous", models.BooleanField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=64)),
                ("race_ethnicity", models.CharField(max_length=64)),
                ("parental_level_of_education", models.CharField(max_length=64)),
                ("lunch", models.CharField(max_length=64)),
                ("test_preparation_course", models.CharField(max_length=64)),
                ("math_score", models.IntegerField()),
                ("reading_score", models.IntegerField()),
                ("predict", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Telecom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=64)),
                ("SeniorCitizen", models.IntegerField()),
                ("Partner", models.CharField(max_length=64)),
                ("Dependents", models.CharField(max_length=64)),
                ("tenure", models.IntegerField()),
                ("PhoneService", models.CharField(max_length=64)),
                ("MultipleLines", models.CharField(max_length=64)),
                ("InternetService", models.CharField(max_length=64)),
                ("OnlineSecurity", models.CharField(max_length=64)),
                ("OnlineBackup", models.CharField(max_length=64)),
                ("DeviceProtection", models.CharField(max_length=64)),
                ("TechSupport", models.CharField(max_length=64)),
                ("StreamingTV", models.CharField(max_length=64)),
                ("StreamingMovies", models.CharField(max_length=64)),
                ("Contract", models.CharField(max_length=64)),
                ("PaperlessBilling", models.CharField(max_length=64)),
                ("PaymentMethod", models.CharField(max_length=64)),
                ("MonthlyCharges", models.FloatField()),
                ("TotalCharges", models.FloatField()),
                ("predict", models.BooleanField(blank=True, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("registered_date", models.DateField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
