# Generated by Django 5.2.9 on 2026-02-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("all_models", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telecom",
            old_name="predict",
            new_name="churn",
        ),
    ]
